server {
    server_name beyondmoney.beyondmebtw.com www.beyondmoney.beyondmebtw.com;

    root /bmbmoney/beyond-money/dist;
    index index.html;

    if ($http_user_agent ~* (AhrefsBot|SemrushBot|MJ12bot|DotBot|BLEXBot|crawler)) {
        return 403;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /robots.txt {
        root /bmbsifi/Beyondmebtw;
    }

    location /assets/ {
        try_files $uri =404;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /beyondmoneyg {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_pass http://localhost:7020;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/beyondmoney.beyondmebtw.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/beyondmoney.beyondmebtw.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = beyondmoney.beyondmebtw.com) {
        return 301 https://$host$request_uri;
    }

    server_name beyondmoney.beyondmebtw.com www.beyondmoney.beyondmebtw.com;
    listen 80;
    return 404;
}
